package:
  name: pyramid
  version: 1.5.1

source:
  fn: pyramid-1.5.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pyramid/pyramid-1.5.1.tar.gz
  md5: 8a1ab3b773d8e22437828f7df22852c1

requirements:
  build:
    - python
    - webob
    - repoze.lru
    - zope.interface
    - zope.deprecation
    - venusian
    - translationstring
    - pastedeploy
    - distribute

  run:
    - python
    - webob
    - repoze.lru
    - zope.interface
    - zope.deprecation
    - venusian
    - translationstring
    - pastedeploy
    - distribute

test:
  imports:
    - pyramid

about:
  home: http://pylonsproject.org
  license: BSD-derived
  summary: "The Pyramid Web Framework, a Pylons project"