package:
  name: jsonschema
  version: !!str 2.4.0

source:
  fn: jsonschema-2.4.0.tar.gz
  url: https://pypi.python.org/packages/source/j/jsonschema/jsonschema-2.4.0.tar.gz
  md5: 661f85c3d23094afbb9ac3c0673840bf

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - jsonschema

about:
  home: http://github.com/Julian/jsonschema
  license: MIT
  summary: "An implementation of JSON Schema validation for Python"