package:
  name: jsonpointer
  version: 1.4

source:
  fn: jsonpointer-1.4.tar.gz
  url: https://pypi.python.org/packages/source/j/jsonpointer/jsonpointer-1.4.tar.gz
  md5: 849debe5e5a55af4d1a641a90e41d525

build:
  preserve_egg_dir: True

requirements:
  build:
    - python

  run:
    - python

test: 
  imports:
    - jsonpointer

about:
  home: https://github.com/stefankoegl/python-json-pointer
  license: Modified BSD License
  summary: "Identify specific nodes in a JSON document (RFC 6901)"